# Generated by Django 6.0.5 on 2026-07-03 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('colleges', '0002_college_email_college_instagram_college_linkedin_and_more'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('placement_status', models.CharField(choices=[('UNPLACED', 'Unplaced'), ('PLACED', 'Placed'), ('INTERN', 'Internship'), ('PLACED_AND_INTERN', 'Placed & Internship')], default='UNPLACED', max_length=20)),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, help_text='LPA package amount if placed', max_digits=10, null=True)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend amount if doing internship', max_digits=10, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='batches.batch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_number'],
                'constraints': [models.UniqueConstraint(fields=('college', 'roll_number'), name='unique_college_roll_number')],
            },
        ),
    ]
