# Generated by Django 6.0.5 on 2026-07-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CGPA out of 10', max_digits=4, null=True),
        ),
    ]
