# Generated by Django 6.0.5 on 2026-07-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlogs',
            field=models.PositiveIntegerField(default=0, help_text='Number of active backlogs'),
        ),
    ]
