# Generated by Django 6.0.5 on 2026-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, help_text='Short personal introduction'),
        ),
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF resume', null=True, upload_to='student_resumes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills e.g. Python, Django, SQL'),
        ),
    ]
