# Generated by Django 6.0.5 on 2026-07-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_address_student_bio_student_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cpi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative Performance Index', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='spi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester Performance Index', max_digits=4, null=True),
        ),
    ]
