# Generated by Django 6.0.5 on 2026-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_cpi_student_spi'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, help_text='Class division/section', max_length=10),
        ),
    ]
