# Generated by Django 6.0.5 on 2026-07-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name e.g. Python, MySQL, Docker', max_length=100)),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('DATABASE', 'Database'), ('CLOUD', 'Cloud'), ('FRAMEWORK', 'Framework'), ('TOOLS', 'Tools'), ('SOFT_SKILLS', 'Soft Skills')], default='PROGRAMMING', max_length=20)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional short note e.g. 3 years of experience', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='students.student')),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'name'), name='unique_student_skill_name')],
            },
        ),
    ]
