# Generated by Django 6.0.5 on 2026-07-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_student_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_resumes/')),
                ('resume_type', models.CharField(choices=[('RESUME', 'Resume'), ('CV', 'CV')], default='RESUME', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('completion_score', models.PositiveIntegerField(default=0)),
                ('formatting_score', models.PositiveIntegerField(default=0)),
                ('projects_found', models.TextField(blank=True, default='[]')),
                ('education_found', models.TextField(blank=True, default='[]')),
                ('skills_found', models.TextField(blank=True, default='[]')),
                ('certificates_found', models.TextField(blank=True, default='[]')),
                ('experience_found', models.TextField(blank=True, default='[]')),
                ('missing_keywords', models.TextField(blank=True, default='[]')),
                ('suggestions', models.TextField(blank=True, default='[]')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to='students.student')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('student', 'resume_type', 'version'), name='unique_student_resumetype_version')],
            },
        ),
    ]
