# Generated by Django 6.0.5 on 2026-07-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_student_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('detailed_description', models.TextField()),
                ('category', models.CharField(choices=[('WEB_DEV', 'Web Development'), ('MOBILE_DEV', 'Mobile Development'), ('DESKTOP', 'Desktop Application'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('DATA_SCIENCE', 'Data Science'), ('CYBER_SEC', 'Cyber Security'), ('CLOUD', 'Cloud Computing'), ('BLOCKCHAIN', 'Blockchain'), ('IOT', 'IoT'), ('GAME_DEV', 'Game Development'), ('AUTOMATION', 'Automation'), ('API_DEV', 'API Development'), ('OTHER', 'Other')], default='WEB_DEV', max_length=50)),
                ('project_type', models.CharField(choices=[('ACADEMIC', 'Academic Project'), ('PERSONAL', 'Personal Project'), ('HACKATHON', 'Hackathon Project'), ('INTERNSHIP', 'Internship Project'), ('FREELANCE', 'Freelance Project'), ('CLIENT', 'Client Project'), ('OPEN_SOURCE', 'Open Source Project')], default='PERSONAL', max_length=50)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ONGOING', 'Ongoing'), ('IN_PROGRESS', 'In Progress'), ('ARCHIVED', 'Archived')], default='COMPLETED', max_length=50)),
                ('technologies', models.TextField(help_text='Comma-separated technologies e.g. Python, Django, PostgreSQL')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('google_drive_url', models.URLField(blank=True)),
                ('figma_url', models.URLField(blank=True)),
                ('play_store_url', models.URLField(blank=True)),
                ('app_store_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 months, 2 weeks', max_length=100)),
                ('is_team_project', models.BooleanField(default=False)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(blank=True, help_text='e.g. Full Stack Developer, ML Engineer', max_length=100)),
                ('key_features', models.TextField(blank=True, help_text='Comma-separated features e.g. User Authentication, REST API')),
                ('achievements', models.TextField(blank=True, help_text='Comma-separated achievements e.g. Hackathon Winner, Innovation Award')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='project_banners/')),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='project_screenshots/')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='project_screenshots/')),
                ('screenshot3', models.ImageField(blank=True, null=True, upload_to='project_screenshots/')),
                ('screenshot4', models.ImageField(blank=True, null=True, upload_to='project_screenshots/')),
                ('architecture_diagram', models.ImageField(blank=True, null=True, upload_to='project_diagrams/')),
                ('workflow_diagram', models.ImageField(blank=True, null=True, upload_to='project_diagrams/')),
                ('demo_gif', models.ImageField(blank=True, null=True, upload_to='project_gifs/')),
                ('project_report', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('source_code_zip', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('research_paper', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('documentation_pdf', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='students.student')),
            ],
            options={
                'ordering': ['-is_featured', '-start_date'],
            },
        ),
    ]
