# Generated by Django 6.0.5 on 2026-07-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='architecture_diagram',
        ),
        migrations.RemoveField(
            model_name='project',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='demo_gif',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation_pdf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_team_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_report',
        ),
        migrations.RemoveField(
            model_name='project',
            name='research_paper',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_code_zip',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='workflow_diagram',
        ),
    ]
