# Generated by Django 6.0.5 on 2026-07-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('students', '0010_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('DAILY_LOG', 'Daily Log'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('CODING_PRACTICE', 'Coding Practice'), ('PROJECT_MILESTONE', 'Project Milestone'), ('HACKATHON', 'Hackathon Journal'), ('CERTIFICATE', 'Certificate'), ('LEARNING_JOURNAL', 'Learning Journal'), ('OPEN_SOURCE', 'Open Source'), ('ACHIEVEMENT', 'Achievement')], default='DAILY_LOG', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('LEARNING', 'Learning'), ('PROJECT', 'Project'), ('CODING_PRACTICE', 'Coding Practice'), ('HACKATHON', 'Hackathon'), ('INTERNSHIP', 'Internship'), ('WORKSHOP', 'Workshop'), ('RESEARCH', 'Research'), ('CERTIFICATE', 'Certificate'), ('COMPETITION', 'Competition'), ('OTHER', 'Other')], default='LEARNING', max_length=50)),
                ('date', models.DateField()),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('technology_tags', models.TextField(blank=True, help_text='Comma-separated technologies')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='journey_attachments/')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='COMPLETED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to='students.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_activities', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LeetCode', 'LeetCode'), ('CodeChef', 'CodeChef'), ('Codeforces', 'Codeforces'), ('HackerRank', 'HackerRank'), ('GeeksforGeeks', 'GeeksforGeeks'), ('Other', 'Other')], default='LeetCode', max_length=50, verbose_name='Platform')),
                ('problems_solved', models.PositiveIntegerField(default=0, verbose_name='Problems Solved')),
                ('difficulty', models.CharField(blank=True, help_text='e.g. 3 Easy, 2 Medium', max_length=100, verbose_name='Difficulty')),
                ('topics', models.TextField(blank=True, help_text='Comma-separated topics e.g. DP, Graphs, HashTables', verbose_name='Topics covered')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Optimal Solutions Learned')),
                ('date', models.DateField(verbose_name='Practice Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_practices', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Achievement Title')),
                ('category', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('RESEARCH_PAPER', 'Research Paper'), ('AWARD', 'Award'), ('INTERNSHIP', 'Internship'), ('COMPETITION', 'Competition'), ('VOLUNTEER', 'Volunteer Work'), ('TECH_CLUB', 'Technical Club'), ('OTHER', 'Other Achievement')], default='AWARD', max_length=50, verbose_name='Category')),
                ('date', models.DateField(verbose_name='Date Achieved')),
                ('description', models.TextField(verbose_name='Description / Details')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='achievement_certs/', verbose_name='Certificate File')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_achievements', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HackathonJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=255, verbose_name='Hackathon Name')),
                ('organizer', models.CharField(max_length=255, verbose_name='Organizer')),
                ('date', models.DateField(verbose_name='Hackathon Date')),
                ('theme', models.CharField(max_length=255, verbose_name='Theme')),
                ('team', models.TextField(blank=True, verbose_name='Team Details')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Your Role')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='Project Built')),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated technologies', verbose_name='Technologies Used')),
                ('challenges', models.TextField(blank=True, verbose_name='Challenges Faced')),
                ('learning', models.TextField(blank=True, verbose_name='Key Learning Outcomes')),
                ('achievement', models.CharField(blank=True, max_length=255, verbose_name='Achievement/Prize')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='hackathon_certs/', verbose_name='Certificate')),
                ('repository', models.URLField(blank=True, verbose_name='Repository Link')),
                ('presentation', models.URLField(blank=True, verbose_name='Presentation / Demo Link')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hackathon_photos/', verbose_name='Photos / Team Banner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathons', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Goal Description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=50, verbose_name='Priority')),
                ('target_date', models.DateField(verbose_name='Target Completion Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50, verbose_name='Goal Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='students.student')),
            ],
            options={
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, verbose_name='Course Name / Topic')),
                ('platform', models.CharField(max_length=100, verbose_name='Platform / Provider')),
                ('duration', models.CharField(blank=True, help_text='e.g. 10 hours, 2 weeks', max_length=100, verbose_name='Duration')),
                ('progress', models.PositiveIntegerField(default=100, help_text='Progress % (e.g. 100 for completed)', verbose_name='Progress %')),
                ('topics', models.TextField(blank=True, help_text='Comma-separated topics learned', verbose_name='Topics Covered')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='learning_certs/', verbose_name='Certificate File')),
                ('notes', models.TextField(blank=True, verbose_name='Learning Notes')),
                ('date', models.DateField(verbose_name='Logging Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('achievements', models.TextField(blank=True, verbose_name='Key Achievements')),
                ('projects_completed', models.TextField(blank=True, verbose_name='Projects Completed')),
                ('technologies_learned', models.TextField(blank=True, verbose_name='Technologies Learned')),
                ('certificates', models.TextField(blank=True, verbose_name='Certificates Acquired')),
                ('goals', models.TextField(blank=True, verbose_name='Goals Set / Completed')),
                ('date', models.DateField(help_text='Starting date or ending date of the month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OpenSourceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=255, verbose_name='GitHub Repository Name')),
                ('contribution', models.TextField(verbose_name='Contribution details')),
                ('pull_request', models.URLField(blank=True, verbose_name='Pull Request URL')),
                ('issue', models.URLField(blank=True, verbose_name='Issue URL')),
                ('date', models.DateField(verbose_name='Contribution Date')),
                ('learning', models.TextField(blank=True, verbose_name='Learning gained')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_source_contributions', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=255, verbose_name='Milestone Name')),
                ('progress_pct', models.PositiveIntegerField(default=0, help_text='Progress from 0 to 100', verbose_name='Progress %')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hours Contributed')),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated technologies', verbose_name='Technologies Used')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=50, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Milestone Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='students.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestones', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('leetcode', models.URLField(blank=True, verbose_name='LeetCode URL')),
                ('codechef', models.URLField(blank=True, verbose_name='CodeChef URL')),
                ('codeforces', models.URLField(blank=True, verbose_name='CodeForces URL')),
                ('hackerrank', models.URLField(blank=True, verbose_name='HackerRank URL')),
                ('geeksforgeeks', models.URLField(blank=True, verbose_name='GeeksforGeeks URL')),
                ('kaggle', models.URLField(blank=True, verbose_name='Kaggle URL')),
                ('portfolio', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_links', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(verbose_name='Week Number')),
                ('summary', models.TextField(verbose_name='Weekly Summary Details')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hours Worked')),
                ('problems_solved', models.PositiveIntegerField(default=0, verbose_name='Problems Solved')),
                ('projects_worked', models.TextField(blank=True, verbose_name='Projects Worked On')),
                ('skills_learned', models.TextField(blank=True, verbose_name='Skills Learned')),
                ('challenges', models.TextField(blank=True, verbose_name='Challenges Faced')),
                ('date', models.DateField(help_text='Usually the Sunday/ending date of the week')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
