# Generated by Django 6.0.5 on 2026-07-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_activity_codingpractice_developerachievement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('COURSE_COMPLETION', 'Course Completion'), ('HACKATHON', 'Hackathon'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('INTERNSHIP', 'Internship'), ('COMPETITION', 'Competition'), ('RESEARCH', 'Research'), ('BOOTCAMP', 'Bootcamp'), ('TRAINING_PROGRAM', 'Training Program'), ('CERTIFICATION_EXAM', 'Certification Exam'), ('VOLUNTEER_PROGRAM', 'Volunteer Program'), ('LEADERSHIP_PROGRAM', 'Leadership Program'), ('COLLEGE_EVENT', 'College Event'), ('OTHER', 'Other')], default='COURSE_COMPLETION', max_length=50)),
                ('issue_date', models.DateField()),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
