# Generated by Django 6.0.5 on 2026-07-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='codechef_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, default='Computer Science & Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, default='B.Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hackerrank_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='higher_studies',
            field=models.CharField(blank=True, help_text='e.g. MS in CS, MBA', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='leetcode_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_job_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_work_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='12th/Diploma Percentage'),
        ),
        migrations.CreateModel(
            name='SemesterPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(help_text='e.g. 1 to 8')),
                ('spi', models.DecimalField(decimal_places=2, help_text='Semester Performance Index (SPI/SGPA)', max_digits=4)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('DETAINED', 'Detained')], default='PASS', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_performances', to='students.student')),
            ],
            options={
                'ordering': ['semester'],
                'constraints': [models.UniqueConstraint(fields=('student', 'semester'), name='unique_student_semester_performance')],
            },
        ),
    ]
