# Generated by Django 6.0.5 on 2026-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_admission_year_student_codechef_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_academic_year',
            field=models.CharField(blank=True, help_text='e.g. 1st Year, 2nd Year, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='semesterperformance',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Current', 'Current'), ('Upcoming', 'Upcoming')], default='Completed', max_length=20),
        ),
    ]
