# Generated by Django 6.0.5 on 2026-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_current_academic_year_student_tenth_board_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresume',
            options={'ordering': ['-is_default', '-uploaded_at']},
        ),
        migrations.RemoveConstraint(
            model_name='studentresume',
            name='unique_student_resumetype_version',
        ),
        migrations.AddField(
            model_name='studentresume',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark as default resume'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='resume_name',
            field=models.CharField(blank=True, help_text='Custom name for the resume', max_length=255),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
