# Generated by Django 6.0.5 on 2026-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studentresume_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Web Development, Cloud, AI/ML', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team Project')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='career_objective',
            field=models.CharField(choices=[('JOB', 'Placement Job'), ('HIGHER_STUDIES', 'Higher Studies'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('BOTH', 'Job & Higher Studies')], default='JOB', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected Salary in LPA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='willing_to_relocate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='work_preference',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite'), ('ANY', 'Open to Any')], default='ANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, null=True, verbose_name='Credential URL'),
        ),
    ]
