# Generated by Django 6.0.5 on 2026-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_certificate_category_certificate_credential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='parser_confidence',
            field=models.PositiveIntegerField(default=0, help_text='0-100% confidence score'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='parser_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='programming_languages_found',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='soft_skills_found',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='tools_found',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
