# Generated by Django 6.0.5 on 2026-07-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_college_email_college_instagram_college_linkedin_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Package in LPA', max_digits=10, null=True)),
                ('job_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-site')], default='ON_SITE', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='colleges.college')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
