# Generated by Django 6.0.5 on 2026-07-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('placements', '0001_initial'),
        ('students', '0003_student_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='drive_type',
            field=models.CharField(choices=[('JOB', 'Job Drive'), ('INTERNSHIP', 'Internship Drive')], default='JOB', max_length=20),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='eligible_departments',
            field=models.ManyToManyField(blank=True, related_name='eligible_drives', to='departments.department'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='max_backlogs',
            field=models.PositiveIntegerField(default=0, help_text='Maximum active backlogs allowed'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='min_cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum CGPA required', max_digits=4),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='selection_process',
            field=models.TextField(blank=True, help_text='Details of selection rounds (e.g. Resume Shortlisting -> Test -> Technical -> HR)'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='package_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package in LPA (or Stipend per month for internships)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('resume', models.FileField(blank=True, help_text='Custom resume for this application', null=True, upload_to='student_resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
            ],
            options={
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('drive', 'student'), name='unique_drive_student_application')],
            },
        ),
    ]
