# Generated by Django 6.0.5 on 2026-07-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_description_batch_division_batch_semester'),
        ('placements', '0002_placementdrive_drive_type_and_more'),
        ('students', '0008_add_student_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='eligible_batches',
            field=models.ManyToManyField(blank=True, related_name='eligible_drives', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated required skills (e.g. Python, SQL)'),
        ),
        migrations.CreateModel(
            name='DriveBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='placements.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_bookmarks', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'drive'), name='unique_student_drive_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='PlacementCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('DEADLINE', 'Application Deadline'), ('TEST', 'Aptitude/Technical Test'), ('INTERVIEW', 'Interview Round'), ('PPT', 'Pre-Placement Talk')], default='DEADLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='placements.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='students.student')),
            ],
            options={
                'ordering': ['event_date', 'event_type'],
                'constraints': [models.UniqueConstraint(fields=('student', 'drive', 'event_type'), name='unique_student_drive_event_type')],
            },
        ),
    ]
