# Generated by Django 6.0.5 on 2026-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_add_bookmark_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementcalendarevent',
            name='event_type',
            field=models.CharField(choices=[('DEADLINE', 'Application Deadline'), ('APTITUDE_TEST', 'Aptitude Test'), ('TECH_INTERVIEW', 'Technical Interview'), ('HR_INTERVIEW', 'HR Interview'), ('OFFER_RELEASE', 'Offer Release'), ('JOINING_DATE', 'Joining Date')], default='DEADLINE', max_length=20),
        ),
    ]
