# Generated by Django 6.0.5 on 2026-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_alter_placementcalendarevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional supporting document (PDF, DOCX)', null=True, upload_to='drive_attachments/'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='job_description',
            field=models.TextField(blank=True, help_text='Full description of the role'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='location',
            field=models.CharField(blank=True, help_text='Job/Internship location', max_length=255),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Key responsibilities for the role'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, help_text='Number of open positions'),
        ),
    ]
