# Generated by Django 6.0.5 on 2026-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COLLEGE_ADMIN', 'College Admin'), ('STUDENT', 'Student'), ('COMPANY', 'Company')], default='STUDENT', max_length=20),
        ),
    ]
