# Generated by Django 6.0.5 on 2026-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COLLEGE_ADMIN', 'College Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
