# Generated by Django 6.0.5 on 2026-07-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='college',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='college',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CampusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campus_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_images', to='colleges.college')),
            ],
        ),
    ]
