# Generated by Django 6.0.5 on 2026-07-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2027 Information Technology', max_length=255)),
                ('graduation_year', models.PositiveIntegerField(help_text='e.g. 2027')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='departments.department')),
            ],
            options={
                'ordering': ['-graduation_year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('department', 'name'), name='unique_department_batch_name')],
            },
        ),
    ]
