# Generated by Django 6.0.5 on 2026-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='division',
            field=models.CharField(blank=True, help_text='e.g. Division A', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current Semester (e.g. 1 to 8)'),
        ),
    ]
