# Generated by Django 6.0.5 on 2026-07-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_college_email_college_instagram_college_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('hr_name', models.CharField(blank=True, max_length=255)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('hr_phone', models.CharField(blank=True, max_length=20)),
                ('hr_notes', models.TextField(blank=True, help_text='Any additional HR contact details or notes')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Package Offered (LPA) e.g. 12.50', max_digits=10, null=True)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly Stipend Offered e.g. 25000', max_digits=10, null=True)),
                ('job_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-site')], default='ON_SITE', max_length=20)),
                ('placement_history', models.TextField(blank=True, help_text='Summary of past recruits, years, and performance from this college')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='colleges.college')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('college', 'name'), name='unique_college_company_name')],
            },
        ),
    ]
