# Generated by Django 6.0.5 on 2026-07-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_about_company_company_company_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
