# Generated by Django 6.0.5 on 2026-07-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_college_email_college_instagram_college_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('package', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('deadline', models.CharField(blank=True, max_length=255)),
                ('source', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('trust_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_opportunities', to='colleges.college')),
            ],
            options={
                'ordering': ['-trust_score', '-created_at'],
            },
        ),
    ]
