# Generated by Django 6.0.5 on 2026-07-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_college_email_college_instagram_college_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='e.g. CSE, ECE, ME', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='colleges.college')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('college', 'code'), name='unique_college_department_code'), models.UniqueConstraint(fields=('college', 'name'), name='unique_college_department_name')],
            },
        ),
    ]
