# Generated by Django 6.0.5 on 2026-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.CharField(blank=True, help_text='Name of Head of Department', max_length=255),
        ),
    ]
